repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  # --- backend hooks ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        name: ruff (backend)
        args: [--fix]
        additional_dependencies: []
        types: [python]
        files: ^backend/.*\.py$
      - id: ruff-format
        name: ruff-format (backend)
        additional_dependencies: []
        types: [python]
        files: ^backend/.*\.py$

  # --- frontend hooks ---
  - repo: https://github.com/biomejs/pre-commit
    rev: v1.9.4
    hooks:
      - id: biome-check
        name: biome-check (frontend)
        files: ^frontend/.*\.(js|jsx|ts|tsx|json)$
        args: ["--config-path", "frontend/biome.json"]
