services:
  backend:
    build:
      context: ./backend
    container_name: "backend"
    command: ["/bin/sh", "-c", "uv run piccolo migrations forward all && uv run litestar run"]
    env_file:
      - .env
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv

  db:
    image: postgres:17
    container_name: "db"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
