# https://taskfile.dev

version: '3.17'

vars:
  DOCKER_COMPOSE: docker compose

tasks:
  build:
    desc: Build all services (with cache)
    cmds:
      - "{{.DOCKER_COMPOSE}} build"

  build:no-cache:
    desc: Build all services without cache
    cmds:
      - "{{.DOCKER_COMPOSE}} build --no-cache"

  up:
    desc: Start all services
    cmds:
      - "{{.DOCKER_COMPOSE}} up"

  down:
    desc: Stop all services
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  down:volumes:
    desc: Stop all services and remove volumes
    aliases: [down:v]
    cmds:
      - "{{.DOCKER_COMPOSE}} down -v"

  backend:lint:fix:
    desc: Run backend lint:fix
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend task lint:fix"

  backend:format:
    desc: Run backend format
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend task format"

  backend:test:
    desc: Run backend tests
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend task test"

  backend:test:cov:
    desc: Run backend tests with coverage
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend task test:cov"

  backend:test:cov:html:
    desc: Run backend tests with coverage and HTML report
    cmds:
      - "{{.DOCKER_COMPOSE}} exec backend task test:cov:html"
