# https://taskfile.dev

version: '3.17'

vars:
  DOCKER_COMPOSE: docker compose
  BACKEND_TASK: "{{.DOCKER_COMPOSE}} exec backend task"
  FRONTEND_TASK: "{{.DOCKER_COMPOSE}} exec frontend task"

tasks:
  build:
    desc: Build all services (with cache)
    cmds:
      - "{{.DOCKER_COMPOSE}} build"

  build:no-cache:
    desc: Build all services without cache
    cmds:
      - "{{.DOCKER_COMPOSE}} build --no-cache"

  up:
    desc: Start all services
    cmds:
      - "{{.DOCKER_COMPOSE}} up"

  down:
    desc: Stop all services
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  down:volumes:
    desc: Stop all services and remove volumes
    aliases: [down:v]
    cmds:
      - "{{.DOCKER_COMPOSE}} down -v"

  backend:lint:fix:
    desc: Run backend lint:fix
    cmds:
      - "{{.BACKEND_TASK}} lint:fix"

  backend:format:
    desc: Run backend format
    cmds:
      - "{{.BACKEND_TASK}} format"

  backend:test:
    desc: Run backend tests
    cmds:
      - "{{.BACKEND_TASK}} test"

  backend:test:cov:
    desc: Run backend tests with coverage
    cmds:
      - "{{.BACKEND_TASK}} test:cov"

  backend:test:cov:html:
    desc: Run backend tests with coverage and HTML report
    cmds:
      - "{{.BACKEND_TASK}} test:cov:html"

  frontend:lint:
    desc: Run Biome linter
    cmds:
      - "{{.FRONTEND_TASK}} lint"

  frontend:format:
    desc: Format code using Biome
    cmds:
      - "{{.FRONTEND_TASK}} format"

  frontend:check:
    desc: Check Biome rules and apply safe fixes (incl. formatting)
    cmds:
      - "{{.FRONTEND_TASK}} check"

  frontend:check:unsafe:
    desc: Check Biome rules and apply all fixes (incl. unsafe and formatting)
    cmds:
      - "{{.FRONTEND_TASK}} check:unsafe"

  frontend:test:run:
    desc: Run all unit/component tests (Vitest) once
    cmds:
      - "{{.FRONTEND_TASK}} test:run"

  frontend:test:ui:
    desc: Run unit/component tests (Vitest) with interactive UI, available at http://localhost:51204/__vitest__/
    cmds:
      - "{{.FRONTEND_TASK}} test:ui"

  frontend:coverage:
    desc: Generate unit/component test (Vitest) coverage report
    cmds:
      - "{{.FRONTEND_TASK}} coverage"

  frontend:test:e2e:
    desc: Run end-to-end tests (Playwright) headlessly
    cmds:
      - "{{.FRONTEND_TASK}} test:e2e"
