# https://taskfile.dev

version: '3.17'

vars:
  DOCKER_COMPOSE: docker compose

tasks:
  build:
    desc: Build all services (with cache)
    cmds:
      - "{{.DOCKER_COMPOSE}} build"

  build:no-cache:
    desc: Build all services without cache
    cmds:
      - "{{.DOCKER_COMPOSE}} build --no-cache"

  up:
    desc: Start all services
    cmds:
      - "{{.DOCKER_COMPOSE}} up"

  down:
    desc: Stop all services
    cmds:
      - "{{.DOCKER_COMPOSE}} down"

  down:volumes:
    desc: Stop all services and remove volumes
    aliases: [down:v]
    cmds:
      - "{{.DOCKER_COMPOSE}} down -v"
