# https://taskfile.dev

version: '3.17'

vars:
  GREETING: Hello, World!

tasks:
  build:
    desc: Build all services (with cache)
    cmds:
      - docker compose build

  build:no-cache:
    desc: Build all services without cache
    cmds:
      - docker compose build --no-cache

  up:
    desc: Start all services
    cmds:
      - docker compose up

  down:
    desc: Stop all services
    cmds:
      - docker compose down

  down:volumes:
    desc: Stop all services and remove volumes
    aliases: [down:v]
    cmds:
      - docker compose down -v
