name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-lint-and-test:
    name: Frontend Lint and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: '10.8.1'

      - name: Get pnpm store directory
        id: pnpm-store
        shell: bash
        run: |
          echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-store.outputs.store_path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        working-directory: ./frontend
        run: pnpm install

      - name: Lint
        working-directory: ./frontend
        run: pnpm lint

      - name: Format Check
        working-directory: ./frontend
        run: pnpm biome check --no-errors-on-unmatched

      - name: Run Tests
        working-directory: ./frontend
        run: pnpm test:run

  backend-lint-and-test:
    name: Backend Lint and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_TEST_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        working-directory: ./backend
        run: uv sync

      - name: Lint with ruff
        working-directory: ./backend
        run: |
          uv run ruff check --force-exclude --fix

      - name: Format check with ruff
        working-directory: ./backend
        run: |
          uv run ruff format --check

      - name: Type check with pyright
        working-directory: ./backend
        run: |
          uv run pyright

      - name: Run tests
        working-directory: ./backend
        run: |
          PICCOLO_CONF=backend.config.piccolo_test uv run pytest
